### ISSUE TITLE
Doesn't work when find-replace panel is displayed

### ISSUE THREAD

**Issue by jakubhruby** [guillaume86/tab-history#10]
### Steps to reproduce
1. Open more than 2 tabs
2. Open find-replace panel (ctrl-f)
3. Use ctrl-tab to switch between the last two tabs
### Expected result
- You are switching between the last two tabs 
### Actual result
- You are browsing through all the tabs
#### Environment
- Windows 7
- Atom 0.191.0
- tab-history 0.4.0

**Comment by jakubhruby** [comment]
The project seems to be discontinued.

**Comment by guillaume86** [comment]
There is a native option now if I remember well (I switched to VS Code personally).
