### ISSUE TITLE
Feature request: last tab when closing tab

### ISSUE THREAD

**Issue by timscott** [guillaume86/tab-history#3]
When closing a tab (esp with the keyboard, CMD-W) instead of going back to the last tab in the stack, it goes to the tab to the left. It would be very natural and expected to in instead go back to the last tab. Possible?

**Comment by guillaume86** [comment]
Yes I also noticed it, I'll take a look into that

2014-12-15 23:11 GMT+01:00 Tim Scott notifications@github.com:

**Comment by guillaume86** [comment]
I added support for MRU switch on tab closing. You can update the package to test it.

**Comment by timscott** [comment]
Works great. Atom is one step closer to perfect. Thanks!!!
